### ISSUE TITLE
The file "regcount_mode1.mat" is missing.

### ISSUE THREAD

**Issue by pengxiaotu** [kendrickkay/nsdexamples#1]
I tried to run all the examples and I found the file  "regcount_mode1.mat" in Examples 7 & 8 is missing. 

**a1 = load('~/Dropbox/nsdabudhabi/nsdextensions/NSD_Annotation_Efforts_1.0/Automated/Faces/regcount_mode1.mat');**

Could you please upload this file or tell me where to download it?

**Comment by kendrickkay** [comment]
you can find that file here: https://www.dropbox.com/scl/fi/aozt1aqgv947a1t5ox8og/regcount_mode1.mat?rlkey=kpeo7jgvx6wh9ykpyzy6lihe6&dl=0
